//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouvenirShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> SouvenirID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PaymentType { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
        public virtual User User { get; set; }
        public virtual Souvenir Souvenir { get; set; }
    }
}
