//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouvenirShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Souvenir
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Souvenir()
        {
            this.DeliveryPlans = new HashSet<DeliveryPlan>();
            this.Warehouses = new HashSet<Warehouse>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Sale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryPlan> DeliveryPlans { get; set; }
        public virtual SouvenirsKind SouvenirsKind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
