//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouvenirShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int ID { get; set; }
        public Nullable<int> SouvenirID { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Souvenir Souvenir { get; set; }
    }
}
